#!/usr/bin/env bash
# Resolve the container base images named in config/images.list to immutable
# registry digests and (re)write config/images.lock.
#
# Usage:
#   scripts/lock-images.sh            # re-resolve every tag
#   scripts/lock-images.sh --check    # fail if any pin drifted / is missing
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGES_LIST="$ROOT/config/images.list"
IMAGES_LOCK="$ROOT/config/images.lock"

CHECK_ONLY=0
[ "${1:-}" = "--check" ] && CHECK_ONLY=1

ACCEPT='application/vnd.oci.image.index.v1+json,application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.docker.distribution.manifest.v2+json'

# resolve_digest <registry-host> <repo> <tag>
resolve_digest() {
  local host="$1" repo="$2" tag="$3" token='' auth=()
  if [ "$host" = "registry-1.docker.io" ]; then
    token="$(curl -fsS --retry 3 \
      "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${repo}:pull" |
      sed -n 's/.*"token":"\([^"]*\)".*/\1/p')"
    auth=(-H "Authorization: Bearer $token")
  fi
  curl -fsS --retry 3 -D- -o /dev/null "${auth[@]}" -H "Accept: $ACCEPT" \
    "https://${host}/v2/${repo}/manifests/${tag}" |
    tr -d '\r' | sed -n 's/^[Dd]ocker-[Cc]ontent-[Dd]igest: //p' | tail -n1
}

work="$(mktemp -d)"; trap 'rm -rf "$work"' EXIT

{
  echo "# GENERATED by scripts/lock-images.sh -- do not edit by hand."
  echo "#"
  echo "# Format: <key>|<reference>@<digest>"
  echo "#"
  echo "# Every FROM in docker/Dockerfile and every image the CLI pulls resolves"
  echo "# through this file.  Tags are mutable; digests are not."
} >"$work/images.lock"

while IFS='|' read -r key ref; do
  case "$key" in ''|\#*) continue ;; esac
  key="${key//[[:space:]]/}"; ref="${ref//[[:space:]]/}"
  [ -n "$ref" ] || continue

  name="${ref%%:*}"; tag="${ref##*:}"
  case "$name" in
    *.*/*|*:*/*)  host="${name%%/*}"; repo="${name#*/}" ;;
    */*)          host="registry-1.docker.io"; repo="$name" ;;
    *)            host="registry-1.docker.io"; repo="library/$name" ;;
  esac

  digest="$(resolve_digest "$host" "$repo" "$tag")"
  [ -n "$digest" ] || { echo "lock-images: could not resolve $ref" >&2; exit 1; }
  echo "lock-images: $key  $ref -> $digest" >&2
  echo "${key}|${ref}@${digest}" >>"$work/images.lock"
done <"$IMAGES_LIST"

if [ "$CHECK_ONLY" -eq 1 ]; then
  if diff -u "$IMAGES_LOCK" "$work/images.lock"; then
    echo "lock-images: images.lock is up to date" >&2
  else
    echo "lock-images: images.lock is STALE -- run scripts/lock-images.sh" >&2
    exit 1
  fi
else
  mv "$work/images.lock" "$IMAGES_LOCK"
  echo "lock-images: wrote $IMAGES_LOCK" >&2
fi
