#!/usr/bin/env bash
# Resolve docker/packages.list against the pinned Ubuntu snapshot and (re)write
# docker/packages.lock with exact `name=version` pins plus the SHA256 of each
# top-level .deb as recorded in the snapshot's signed Packages index.
#
# Usage:
#   scripts/lock-apt.sh                      # re-lock at the current snapshot
#   scripts/lock-apt.sh --snapshot 20260801T000000Z
#   scripts/lock-apt.sh --check              # fail if the lock is stale
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SNAPSHOT_LOCK="$ROOT/docker/apt-snapshot.lock"
PKG_LIST="$ROOT/docker/packages.list"
PKG_LOCK="$ROOT/docker/packages.lock"
BASE_URL="https://snapshot.ubuntu.com/ubuntu"

CHECK_ONLY=0
SNAPSHOT_OVERRIDE=""
while [ $# -gt 0 ]; do
  case "$1" in
    --check) CHECK_ONLY=1 ;;
    --snapshot) SNAPSHOT_OVERRIDE="$2"; shift ;;
    -h|--help) sed -n '2,10p' "$0"; exit 0 ;;
    *) echo "lock-apt: unknown argument: $1" >&2; exit 2 ;;
  esac
  shift
done

# shellcheck disable=SC1090
. "$SNAPSHOT_LOCK"
[ -n "$SNAPSHOT_OVERRIDE" ] && APT_SNAPSHOT="$SNAPSHOT_OVERRIDE"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "lock-apt: snapshot=$APT_SNAPSHOT suite=$APT_SUITE" >&2

# --- fetch every Packages index in the pinned snapshot ----------------------
for pocket in $APT_POCKETS; do
  for comp in $APT_COMPONENTS; do
    url="$BASE_URL/$APT_SNAPSHOT/dists/$pocket/$comp/binary-amd64/Packages.gz"
    if curl -fsS --retry 3 --retry-delay 2 -o "$work/idx.gz" "$url"; then
      gzip -dc "$work/idx.gz" >>"$work/Packages"
      printf '\n' >>"$work/Packages"
      echo "lock-apt:   + $pocket/$comp" >&2
    else
      echo "lock-apt:   - $pocket/$comp (absent)" >&2
    fi
  done
done
[ -s "$work/Packages" ] || { echo "lock-apt: no package indexes fetched" >&2; exit 1; }

# --- flatten stanzas to "name<TAB>version<TAB>sha256" ------------------------
awk '
  /^Package: /  { pkg = $2 }
  /^Version: /  { ver = $2 }
  /^SHA256: /   { sha = $2 }
  /^$/          { if (pkg != "") print pkg "\t" ver "\t" sha; pkg=""; ver=""; sha="" }
  END           { if (pkg != "") print pkg "\t" ver "\t" sha }
' "$work/Packages" >"$work/flat"

grep -vE '^\s*(#|$)' "$PKG_LIST" | tr -d '\r' | sed 's/[[:space:]]*$//' | sort -u >"$work/wanted"

# --- pick the highest version per wanted package ----------------------------
missing=0
: >"$work/resolved"
while read -r name; do
  [ -n "$name" ] || continue
  best="$(awk -F'\t' -v n="$name" '$1 == n { print }' "$work/flat" |
          sort -t"$(printf '\t')" -k2,2V | tail -n1)"
  if [ -z "$best" ]; then
    echo "lock-apt: ERROR package not found in snapshot: $name" >&2
    missing=1
    continue
  fi
  printf '%s\n' "$best" >>"$work/resolved"
done <"$work/wanted"
[ "$missing" -eq 0 ] || exit 1

# --- render the lock file ---------------------------------------------------
{
  echo "# GENERATED by scripts/lock-apt.sh -- do not edit by hand."
  echo "#"
  echo "# Format: <name>=<version>  # sha256:<digest of the amd64 .deb>"
  echo "#"
  echo "# The snapshot in docker/apt-snapshot.lock is the authoritative pin: it"
  echo "# freezes the full transitive closure.  The versions below pin the"
  echo "# top-level set explicitly so that a snapshot bump shows up as a"
  echo "# reviewable diff instead of a silent change."
  echo "#"
  echo "# snapshot: $APT_SNAPSHOT"
  echo "# suite:    $APT_SUITE"
  echo "# arch:     amd64"
  awk -F'\t' '{ printf "%s=%s  # sha256:%s\n", $1, $2, $3 }' "$work/resolved" | sort
} >"$work/packages.lock"

if [ "$CHECK_ONLY" -eq 1 ]; then
  if diff -u "$PKG_LOCK" "$work/packages.lock"; then
    echo "lock-apt: packages.lock is up to date" >&2
  else
    echo "lock-apt: packages.lock is STALE -- run scripts/lock-apt.sh" >&2
    exit 1
  fi
else
  mv "$work/packages.lock" "$PKG_LOCK"
  echo "lock-apt: wrote $PKG_LOCK ($(grep -c '=' "$PKG_LOCK") packages)" >&2
fi
